// default package
// Generated 22 May, 2021 11:24:08 AM by Hibernate Tools 5.2.3.Final
package com.java.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "icfdata")
public class Employee implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String employeeid;
	private String startdate;
	private String enddate;
	private String designation;
	private String dob;
	private String status;
	private String reportingmanager;
	private String gender;
	private String address;
	private String institution;
	private String percentage;
	private String relationship;
	private String type;
	private String bloodgroup;

	public Employee() {
	}

	public Employee(String firstname, String lastname, String employeeid, String startdate, String enddate,
			String designation, String dob, String status, String reportingmanager, String gender, String address,
			String institution, String percentage, String relationship, String type, String bloodgroup) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.employeeid = employeeid;
		this.startdate = startdate;
		this.enddate = enddate;
		this.designation = designation;
		this.dob = dob;
		this.status = status;
		this.reportingmanager = reportingmanager;
		this.gender = gender;
		this.address = address;
		this.institution = institution;
		this.percentage = percentage;
		this.relationship = relationship;
		this.type = type;
		this.bloodgroup = bloodgroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "employeeid", length = 45)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "startdate", length = 45)
	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate", length = 45)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "designation", length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "dob", length = 45)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reportingmanager", length = 45)
	public String getReportingmanager() {
		return this.reportingmanager;
	}

	public void setReportingmanager(String reportingmanager) {
		this.reportingmanager = reportingmanager;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "institution", length = 45)
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	@Column(name = "percentage", length = 45)
	public String getPercentage() {
		return this.percentage;
	}

	public void setPercentage(String percentage) {
		this.percentage = percentage;
	}

	@Column(name = "relationship", length = 45)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "bloodgroup", length = 45)
	public String getBloodgroup() {
		return this.bloodgroup;
	}

	public void setBloodgroup(String bloodgroup) {
		this.bloodgroup = bloodgroup;
	}

}
